rocketmq:
  consumer:
#    rocketmq的请求地址
    namesrvAddr: 127.0.0.1:9876
#    发送同一类消息的设置为同一个group，保证唯一，默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: mallpf
#    如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: consumer.mallpf
  producer:
#    发送消息超时时间
    sendMsgTimeout: 10000
#    最大消息限制
    maxMessageSize: 9999999
#    消息大小超出配置对消息压缩
    compressOver: 40000
  topic: topic-mallpf
  tag: tag-mallpf